query {
    home: HomepageItem(id: "home") {
        id
        content {
            _editable
            _uid
            title
            sub_title
            skills
            testimonials
        }
    }

    blog_posts: BlogpostItems {
        items {
            created_at
            content {
                image
                title
                content
            }
        }
    }
}
